services:
  signoz:
    image: signoz/signoz-community:${VERSION:-v0.113.0}
    container_name: signoz
    ports:
      - "8080:8080" # signoz port
    volumes:
      - sqlite:/var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://${CLICKHOUSE_URL}
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - SIGNOZ_TOKENIZER_JWT_SECRET=${SIGNOZ_TOKEN_SECRET}
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
  otel-collector:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.144.1}
    container_name: signoz-otel-collector
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate sync check &&
        /signoz-otel-collector --config=/etc/otel-collector-config.yaml --manager-config=/etc/manager-config.yaml --copy-path=/var/tmp/collector-config.yaml
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./config/otel-collector-opamp-config.yaml:/etc/manager-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://${CLICKHOUSE_URL}
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "13133:13133" # health check

networks:
  signoz-net:
    name: stand-signoz-net
volumes:
  sqlite:
    name: stand-signoz-sqlite